<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
  <meta charset="utf-8">
  <meta name="generator" content="quarto-0.9.183">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  <title>The Cifti Data Structure in R</title>
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    span.underline{text-decoration: underline;}
    div.column{display: inline-block; vertical-align: top; width: 50%;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      {   }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span.al { color: #ff0000; font-weight: bold; } /* Alert */
    code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
    code span.at { color: #7d9029; } /* Attribute */
    code span.bn { color: #40a070; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #4070a0; } /* Char */
    code span.cn { color: #880000; } /* Constant */
    code span.co { color: #60a0b0; font-style: italic; } /* Comment */
    code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
    code span.do { color: #ba2121; font-style: italic; } /* Documentation */
    code span.dt { color: #902000; } /* DataType */
    code span.dv { color: #40a070; } /* DecVal */
    code span.er { color: #ff0000; font-weight: bold; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #40a070; } /* Float */
    code span.fu { color: #06287e; } /* Function */
    code span.im { } /* Import */
    code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
    code span.kw { color: #007020; font-weight: bold; } /* Keyword */
    code span.op { color: #666666; } /* Operator */
    code span.ot { color: #007020; } /* Other */
    code span.pp { color: #bc7a00; } /* Preprocessor */
    code span.sc { color: #4070a0; } /* SpecialChar */
    code span.ss { color: #bb6688; } /* SpecialString */
    code span.st { color: #4070a0; } /* String */
    code span.va { color: #19177c; } /* Variable */
    code span.vs { color: #4070a0; } /* VerbatimString */
    code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
  </style>

  <script src="cifti-r_files/libs/clipboard/clipboard.min.js"></script>
  <script src="cifti-r_files/libs/quarto-html/quarto.js"></script>
  <script src="cifti-r_files/libs/quarto-html/popper.min.js"></script>
  <script src="cifti-r_files/libs/quarto-html/tippy.umd.min.js"></script>
  <script src="cifti-r_files/libs/quarto-html/anchor.min.js"></script>
  <link href="cifti-r_files/libs/quarto-html/tippy.css" rel="stylesheet">
  <link class="quarto-color-scheme" id="quarto-text-highlighting-styles" href="cifti-r_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet">
  <link class="quarto-color-scheme quarto-color-alternate" rel="prefetch" id="quarto-text-highlighting-styles" href="cifti-r_files/libs/quarto-html/quarto-syntax-highlighting-dark.css">
  <script src="cifti-r_files/libs/bootstrap/bootstrap.min.js"></script>
  <link href="cifti-r_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
  <link class="quarto-color-scheme" href="cifti-r_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet">
  <link class="quarto-color-scheme quarto-color-alternate" rel="prefetch" href="cifti-r_files/libs/bootstrap/bootstrap-dark.min.css">
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
</head>
<body>
<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc">
<h2 id="toc-title">Table of contents</h2>
<ul>
<li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
<li><a href="#gifti" id="toc-gifti" class="nav-link" data-scroll-target="#gifti">GIFTI</a>
<ul class="collapse">
<li><a href="#surfaces" id="toc-surfaces" class="nav-link" data-scroll-target="#surfaces">Surfaces</a>
<ul class="collapse">
<li><a href="#metadata" id="toc-metadata" class="nav-link" data-scroll-target="#metadata">Metadata</a></li>
</ul></li>
<li><a href="#metric-and-label-data" id="toc-metric-and-label-data" class="nav-link" data-scroll-target="#metric-and-label-data">Metric and Label Data</a>
<ul class="collapse">
<li><a href="#metric" id="toc-metric" class="nav-link" data-scroll-target="#metric">Metric</a></li>
<li><a href="#label" id="toc-label" class="nav-link" data-scroll-target="#label">Label</a></li>
</ul></li>
</ul></li>
<li><a href="#cifti" id="toc-cifti" class="nav-link" data-scroll-target="#cifti">CIFTI</a>
<ul class="collapse">
<li><a href="#subcortical-area-names" id="toc-subcortical-area-names" class="nav-link" data-scroll-target="#subcortical-area-names">Subcortical Area Names</a></li>
<li><a href="#converting-to-data-frame" id="toc-converting-to-data-frame" class="nav-link" data-scroll-target="#converting-to-data-frame">Converting to Data Frame</a></li>
</ul></li>
</ul>
</nav>
</div>
<main class="content" id="quarto-document-content">
<header id="title-block-header" class="quarto-title-block default">

<div class="quarto-title"><h1 class="title display-7">The Cifti Data Structure in R</h1></div></header>

<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>The <a href="https://www.humanconnectome.org/software/workbench-command/-cifti-help">CIFTI</a> format is a neuroimaging data format designed by researchers involved with the Human Connectome Project to make working with disjoint data (typically cortical and subcortical) at the same time easier. CIFTI (and GIFTI) are standard outputs from the <a href="https://uab-cinl.github.io/analysis/hcp_pipelines/">HCP Preprocessing Pipeline</a> and can be generated using <a href="https://uab-cinl.github.io/analysis/fmriprep/">fmriprep</a> or <a href="https://github.com/edickie/ciftify">ciftify</a> as well, but very little information exists on how to use these formats during data analysis within different platforms. This guide will cover how to import and use these data structures in R.</p>
<p>All data used in this tutorial comes from the <a href="https://www.humanconnectome.org/study/hcp-young-adult">HCP Young Adult Dataset</a>. These data are freely available for research or learning purposes from their <a href="db.humanconnectome.org">online repository</a>. The exact subject numbers won’t be shared here, but all participants in that study who had at least one MRI session will have the same data files. If you would like to practice on these data, you can download the Preprocessed data for some participants, but be aware a full preprocessed dataset can be upwards of 60 GB per person. Here, we will only look at structural preprocessed data (derived from T1w and T2w) and a single preprocessed resting state scan.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Packages specific to gifti and cifti structures will be introduced below, but we will also be using the <a href="https://www.tidyverse.org/">tidyverse</a> suite of packages for data wrangling as well.</p>
</div>
</div>
<div class="cell">

</div>
</section>
<section id="gifti" class="level2">
<h2 class="anchored" data-anchor-id="gifti">GIFTI</h2>
<p>We will start with gifti because it is an easier format to understand and will help organize cifti data later on. All gifti data can be loaded using the <a href="https://cran.r-project.org/web/packages/gifti/index.html">gifti</a> library which can be downloaded from CRAN.</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gifti)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>All gifti data will be loaded using the <code>read_gifti</code> command. <code>readgii</code> and <code>readGIFTI</code> are both aliases for <code>read_gifti</code> and so can be used the same way as well if you prefer typing one of those. The output of these commands will be a named list.</p>
<section id="surfaces" class="level3">
<h3 class="anchored" data-anchor-id="surfaces">Surfaces</h3>
<p>All gifti files describe some form of information about a single cortical hemisphere, no subcortical information is included. All generated gifti files from a standard preprocessing pipeline will include which hemisphere the gifti describes in the name (a practice everyone should use). The most common giftis will be the structural surfaces themselves that other data are shown on. These files always end with the <code>surf.gii</code> extension.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/pial_surface.png" class="img-fluid figure-img"></p>
</figure>
</div>
<p>As said above, these surfaces can be imported using one of gifti’s <code>read</code> functions.</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>lhpial <span class="ot">&lt;-</span> <span class="fu">read_gifti</span>(<span class="st">'data/102109/fsaverage_LR32k/102109.L.pial.32k_fs_LR.surf.gii'</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>rhpial <span class="ot">&lt;-</span> <span class="fu">read_gifti</span>(<span class="st">'data/102109/fsaverage_LR32k/102109.R.pial.32k_fs_LR.surf.gii'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Lists from gifti files are going to have 8 top-level fields with the following names:</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(lhpial)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>[1] "data"                   "file_meta"              "data_meta"             
[4] "version"                "transformations"        "parsed_transformations"
[7] "label"                  "data_info"             </code></pre>
</div>
</div>
<p>Most of the interesting information is in the <code>data</code> field of the output list.</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(lhpial<span class="sc">$</span>data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>List of 2
 $ pointset: num [1:32492, 1:3] -4 -21.79 -52.8 -4.21 -25.59 ...
 $ triangle: int [1:64980, 1:3] 68 180 180 181 181 182 182 183 183 184 ...</code></pre>
</div>
</div>
<p>You can see that for the lh pial surface, <code>data</code> has two subfields: <code>pointset</code> and <code>triangle</code>. <code>pointset</code> gives the spatial coordinates for each vertex on the surface which will change between pial, inflated, very inflated, etc. surfaces, and <code>triangle</code> gives a list of vertices that make up each face which does not change between surfaces. The actual data in the <code>pointset</code> and <code>triangle</code> fields won’t be useful that often, the important part is the total number of vertices which you can get from the number of rows in <code>pointset</code>. You can see this surface has 32492 vertices, and the right hemisphere surfaces also have 32492 vertices. The <code>fsaverage_LR32k</code> surfaces are in a template space, and each surface should have the same number of vertices across participants. The same goes for the 164k surfaces, but the number of vertices is larger. If you’re working with the native space surfaces, the number of vertices will be dependent on subject and hemisphere.</p>
<section id="metadata" class="level4">
<h4 class="anchored" data-anchor-id="metadata">Metadata</h4>
<p>Other data of interest in the surface files can be found in the <code>data_meta</code> field such as the primary and secondary structure the surface describes in case this information was left out of the file name.</p>
</section>
</section>
<section id="metric-and-label-data" class="level3">
<h3 class="anchored" data-anchor-id="metric-and-label-data">Metric and Label Data</h3>
<p>All other gifti files should have extensions such as <code>func.gii</code>, <code>shape.gii</code>, or <code>label.gii</code>. These contain data that describe some property of vertices on the surface such as thickness, curvature, or timeseries data. Again, these can also be loaded using one of the <code>read</code> commands above.</p>
<section id="metric" class="level4">
<h4 class="anchored" data-anchor-id="metric">Metric</h4>
<p>Metric data contain continuous values and are stored in <code>func.gii</code> or <code>shape.gii</code> files depending on whether the data describe functional or structural information. For example, we can load the thickness surfaces. The surface overlays can be seen below.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/pial_thickness.png" class="img-fluid figure-img"></p>
</figure>
</div>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>lhthick <span class="ot">&lt;-</span> <span class="fu">read_gifti</span>(<span class="st">'data/102109/fsaverage_LR32k/102109.L.thickness.32k_fs_LR.shape.gii'</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>rhthick <span class="ot">&lt;-</span> <span class="fu">read_gifti</span>(<span class="st">'data/102109/fsaverage_LR32k/102109.R.thickness.32k_fs_LR.shape.gii'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>These surfaces will have the same fields as the surface files.</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(lhthick)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>[1] "data"                   "file_meta"              "data_meta"             
[4] "version"                "transformations"        "parsed_transformations"
[7] "label"                  "data_info"             </code></pre>
</div>
</div>
<p>Similar to last time, the <code>data</code> field is the one of main interest and will contain at least one subfield, <code>normal</code> in this case.</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(lhthick<span class="sc">$</span>data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>List of 1
 $ normal: num [1:32492, 1] 3.16 2.27 3.05 3.5 2.22 ...</code></pre>
</div>
</div>
<p>For all metric giftis, the number of values equals the number of vertices on the surface. This is the case even if some vertices would not have a reasonable value. For example, vertices making up the medial wall do not have a calculated thickness and are uncolored in the above image. The thickness gifti assigns a numeric value to them anyway since those vertices need to be accounted for and will assign a value of 0 in this case. This is not the case for cifti data which will be seen later. There are 29696 vertices on the left hemisphere and 29716 on the right that have a measurable thickness.</p>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Base-0 and Base-1 Indexing
</div>
</div>
<div class="callout-body-container callout-body">
<p>Be aware that R uses base-1 indexing, but the vertex numbering system is base-0. This means that vertex 0 on the surface has the thickness value assigned at index 1 in R. For example, we can get the thickness of vertex 1978 for a participant in wb_view, seen below.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/vertex_thickness.png" class="img-fluid figure-img"></p>
</figure>
</div>
<p>But index 1978 has thickness value 4.08641. To get the correct thickness value for this vertex, you would get the thickness from index 1979 of 3.85193.</p>
</div>
</div>
<p>While thickness data are stored in an array because each vertex only has a single thickness value, functional timeseries data are stored as a matrix. Functional data can be loaded and interacted with the same way though.</p>
<div class="cell" data-hash="cifti-r_cache/html/load functional data_26e028f65b4286babc2451b4f53d55cf">
<div class="sourceCode" id="cb12"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>lhrest_native <span class="ot">&lt;-</span> <span class="fu">read_gifti</span>(<span class="st">'data/102109/Results/rfMRI_REST1_LR/rfMRI_REST1_LR.L.native.func.gii'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Here, we are loading the native space version of the resting state scan because the preprocessed data did not have gifti versions of the functional scans in fs_LR_32k space. The number of vertices will differ, but the idea is exactly the same.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(lhrest_native<span class="sc">$</span>data[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>List of 5
 $ normal: num [1:166272, 1] 7196 7087 7296 6051 6809 ...
 $ normal: num [1:166272, 1] 7273 7145 7323 5948 6840 ...
 $ normal: num [1:166272, 1] 7355 7198 7313 6233 7064 ...
 $ normal: num [1:166272, 1] 7413 7292 7497 6286 7138 ...
 $ normal: num [1:166272, 1] 7424 7261 7408 6295 7069 ...</code></pre>
</div>
<div class="sourceCode" id="cb15"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(lhrest_native<span class="sc">$</span>data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>[1] 1200</code></pre>
</div>
</div>
<p>Now, the <code>data</code> field has more than one subfield, it now has 1200 subfields. This represents the 1200 timepoints in the scan. Each one of the subfields has 166272 values in it representing the scan value at each vertex in that hemisphere for a given timepoint (on the native space surface). Each timepoint is stored as an individual list of functional values within the <code>data</code> field.</p>
<p>Storing timepoints as a series of lists can make the data difficult to work with. We can instead extract the data and store it in a simplified 2D matrix. Columns will represent timepoints which rows represent vertices, the standard representation for CIFTI data.</p>
<div class="cell" data-hash="cifti-r_cache/html/gifti func to matrix_7f7843a4997539153bb9ce77a303f287">
<div class="sourceCode" id="cb17"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>lhrest_native_data <span class="ot">&lt;-</span> <span class="fu">do.call</span>(cbind,lhrest_native<span class="sc">$</span>data)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(lhrest_native_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>[1] 166272</code></pre>
</div>
<div class="sourceCode" id="cb19"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ncol</span>(lhrest_native_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>[1] 1200</code></pre>
</div>
</div>
<p><code>lhrest_native_data</code> has been created as a matrix with 166272 rows each corresponding to a vertex and 1200 columns each corresponding to a timepoint.</p>
<p>An important note is that this matrix takes up a large amount of memory because there are 199526400 elements in the matrix for one hemisphere of one person. When using this sort of data across a large number of participants, you will need a large amount of memory or do some form of summarization as data is being imported using a custom function. This may be the case even for fs_LR_32k space data even though the number of vertices per hemisphere is much smaller than the native space scan used here.</p>
</section>
<section id="label" class="level4">
<h4 class="anchored" data-anchor-id="label">Label</h4>
<p>Label data are made up of integer values that each map to different names, typically for regions of interest or parcellation areas. Here, we will load the aparc label files that are automatically generated and transferred from FreeSurfer.</p>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>lhlabel <span class="ot">&lt;-</span> <span class="fu">read_gifti</span>(<span class="st">'data/102109/fsaverage_LR32k/102109.L.aparc.32k_fs_LR.label.gii'</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>rhlabel <span class="ot">&lt;-</span> <span class="fu">read_gifti</span>(<span class="st">'data/102109/fsaverage_LR32k/102109.R.aparc.32k_fs_LR.label.gii'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>These label files have the same structure as the metric files above where the <code>data</code> field gives the integer assignment for each vertex, but the <code>label</code> field is also used to give a list of names assigned to the integers as well as their RGB value for plotting on a surface.</p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>lhlabel<span class="sc">$</span>label</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>                           Key  Red         Green       Blue        Alpha
???                        "0"  "0"         "0"         "0"         "0"  
L_bankssts                 "1"  "0.0980392" "0.392157"  "0.156863"  "1"  
L_caudalanteriorcingulate  "2"  "0.490196"  "0.392157"  "0.627451"  "1"  
L_caudalmiddlefrontal      "3"  "0.392157"  "0.0980392" "0"         "1"  
L_corpuscallosum           "4"  "0.470588"  "0.27451"   "0.196078"  "1"  
L_cuneus                   "5"  "0.862745"  "0.0784314" "0.392157"  "1"  
L_entorhinal               "6"  "0.862745"  "0.0784314" "0.0392157" "1"  
L_fusiform                 "7"  "0.705882"  "0.862745"  "0.54902"   "1"  
L_inferiorparietal         "8"  "0.862745"  "0.235294"  "0.862745"  "1"  
L_inferiortemporal         "9"  "0.705882"  "0.156863"  "0.470588"  "1"  
L_isthmuscingulate         "10" "0.54902"   "0.0784314" "0.54902"   "1"  
L_lateraloccipital         "11" "0.0784314" "0.117647"  "0.54902"   "1"  
L_lateralorbitofrontal     "12" "0.137255"  "0.294118"  "0.196078"  "1"  
L_lingual                  "13" "0.882353"  "0.54902"   "0.54902"   "1"  
L_medialorbitofrontal      "14" "0.784314"  "0.137255"  "0.294118"  "1"  
L_middletemporal           "15" "0.627451"  "0.392157"  "0.196078"  "1"  
L_parahippocampal          "16" "0.0784314" "0.862745"  "0.235294"  "1"  
L_paracentral              "17" "0.235294"  "0.862745"  "0.235294"  "1"  
L_parsopercularis          "18" "0.862745"  "0.705882"  "0.54902"   "1"  
L_parsorbitalis            "19" "0.0784314" "0.392157"  "0.196078"  "1"  
L_parstriangularis         "20" "0.862745"  "0.235294"  "0.0784314" "1"  
L_pericalcarine            "21" "0.470588"  "0.392157"  "0.235294"  "1"  
L_postcentral              "22" "0.862745"  "0.0784314" "0.0784314" "1"  
L_posteriorcingulate       "23" "0.862745"  "0.705882"  "0.862745"  "1"  
L_precentral               "24" "0.235294"  "0.0784314" "0.862745"  "1"  
L_precuneus                "25" "0.627451"  "0.54902"   "0.705882"  "1"  
L_rostralanteriorcingulate "26" "0.313726"  "0.0784314" "0.54902"   "1"  
L_rostralmiddlefrontal     "27" "0.294118"  "0.196078"  "0.490196"  "1"  
L_superiorfrontal          "28" "0.0784314" "0.862745"  "0.627451"  "1"  
L_superiorparietal         "29" "0.0784314" "0.705882"  "0.54902"   "1"  
L_superiortemporal         "30" "0.54902"   "0.862745"  "0.862745"  "1"  
L_supramarginal            "31" "0.313726"  "0.627451"  "0.0784314" "1"  
L_frontalpole              "32" "0.392157"  "0"         "0.392157"  "1"  
L_temporalpole             "33" "0.27451"   "0.0784314" "0.666667"  "1"  
L_transversetemporal       "34" "0.588235"  "0.588235"  "0.784314"  "1"  
L_insula                   "35" "1"         "0.752941"  "0.12549"   "1"  </code></pre>
</div>
</div>
<p>You can see there’s an integer value 0 in the table that vertices with an unknown assignment might be given instead. Vertices with no label assignment at all will have a value of -1. It will be meaningful to filter out vertices that have values of either 0 or -1 when performing analyses.</p>
</section>
</section>
</section>
<section id="cifti" class="level2">
<h2 class="anchored" data-anchor-id="cifti">CIFTI</h2>
<p>CIFTI files are a file type that can combine data from both hemispheres as well as subcortical regions. All cifti files can be imported using the <a href="https://cran.r-project.org/web/packages/cifti/cifti.pdf">cifti</a> package which can be installed from CRAN. The cifti package also installs <code>gifti</code> as a dependency.</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cifti)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As opposed to gifti, cifti files can contain information about both hemispheres as well as subcortical regions in the same file. The basic import function is <code>read_cifti</code> (<code>readcii</code> and <code>readCIFTI</code> are also aliases). For example, we can go ahead and read in the subject’s thickness cifti file.</p>
<div class="cell" data-hash="cifti-r_cache/html/read thickness_b9b794b3bc1e213a7bbfce2704b825e8">
<div class="sourceCode" id="cb25"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>thick_cii <span class="ot">&lt;-</span> <span class="fu">read_cifti</span>(<span class="st">'data/102109/fsaverage_LR32k/102109.thickness.32k_fs_LR.dscalar.nii'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stderr">
<pre><code>Warning in read_cifti("data/102109/fsaverage_LR32k/
102109.thickness.32k_fs_LR.dscalar.nii"): Dimensions of the data &gt; 2, so no
transposing done!</code></pre>
</div>
</div>
<p>The cifti list structure in R is slightly different from the gifti structure.</p>
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(thick_cii)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>[1] "NamedMap"   "BrainModel" "data"       "hdr"        "filename"  
[6] "drop_data"  "trans_data"</code></pre>
</div>
</div>
<p>Here, we will have a few fields of interest:</p>
<ol type="1">
<li><code>NamedMap</code>: contains a list of map names if multiple maps are stored in the same file. For instance, curvature, thickness, and Myelin values could all be stored in the same CIFTI file.</li>
<li><code>BrainModel</code>: List of brainordinates which have data. Brainordinates from different areas will be stored in different lists within <code>BrainModel</code>. Sometimes, the names of the areas are not given in the structure but can be read directly from the cifti file. See below.</li>
<li><code>data</code>: field containing the data of interest. Data are stored in a 1D array or 2D matrix where rows refer to the brainordinates concatenated from different areas. For 2D data, columns are typically timepoints.</li>
</ol>
<p>As opposed to gifti data from above, only brainordinates that have data assigned to them are given in the <code>data</code> field. In order to accurately assign data to the correct brainordinate and area, you need to use the values from the <code>BrainModel</code> field. For example, let’s look at the thickness cifti file we loaded earlier.</p>
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(thick_cii<span class="sc">$</span>BrainModel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>List of 2
 $ : num [1:29696] 0 1 2 3 4 5 6 8 9 10 ...
  ..- attr(*, "IndexOffset")= num 0
  ..- attr(*, "IndexCount")= num 29696
  ..- attr(*, "BrainStructure")= chr "CIFTI_STRUCTURE_CORTEX_LEFT"
  ..- attr(*, "ModelType")= chr "CIFTI_MODEL_TYPE_SURFACE"
  ..- attr(*, "SurfaceNumberOfVertices")= num 32492
 $ : num [1:29716] 0 1 2 3 4 5 6 8 9 10 ...
  ..- attr(*, "IndexOffset")= num 29696
  ..- attr(*, "IndexCount")= num 29716
  ..- attr(*, "BrainStructure")= chr "CIFTI_STRUCTURE_CORTEX_RIGHT"
  ..- attr(*, "ModelType")= chr "CIFTI_MODEL_TYPE_SURFACE"
  ..- attr(*, "SurfaceNumberOfVertices")= num 32492</code></pre>
</div>
</div>
<p>We can see there are 29696 thickness values assigned to the left cortex and 29716 assigned to the right cortex and the data are the vertex numbers which have thickness data. The <code>data</code> field is concatenated in order of subfields in <code>BrainModel</code>. In other words, the first 29696 rows are left hemisphere data and the last 29716 rows are right hemisphere data if there is only cortical data. For ciftis with both cortical and subcortical areas, subcortical data will be concatenated following the right hemisphere.</p>
<section id="subcortical-area-names" class="level3">
<h3 class="anchored" data-anchor-id="subcortical-area-names">Subcortical Area Names</h3>
<p>While the cortical hemispheres are named in the cifti’s R structure, the subcortical areas are not. For example, we can import a cifti with resting state data for both cortex and subcortical areas and look at the attributes for the first 4 areas.</p>
<div class="cell" data-hash="cifti-r_cache/html/load rest cifti_fa97b0acb11f76ca0d6ac18daafdf232">
<div class="sourceCode" id="cb31"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>rest_cii <span class="ot">&lt;-</span> <span class="fu">read_cifti</span>(<span class="st">'data/102109/Results/rfMRI_REST1_LR/rfMRI_REST1_LR_Atlas.dtseries.nii'</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(rest_cii<span class="sc">$</span>BrainModel[<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>List of 4
 $ : num [1:29696] 0 1 2 3 4 5 6 8 9 10 ...
  ..- attr(*, "IndexOffset")= num 0
  ..- attr(*, "IndexCount")= num 29696
  ..- attr(*, "BrainStructure")= chr "CIFTI_STRUCTURE_CORTEX_LEFT"
  ..- attr(*, "ModelType")= chr "CIFTI_MODEL_TYPE_SURFACE"
  ..- attr(*, "SurfaceNumberOfVertices")= num 32492
 $ : num [1:29716] 0 1 2 3 4 5 6 8 9 10 ...
  ..- attr(*, "IndexOffset")= num 29696
  ..- attr(*, "IndexCount")= num 29716
  ..- attr(*, "BrainStructure")= chr "CIFTI_STRUCTURE_CORTEX_RIGHT"
  ..- attr(*, "ModelType")= chr "CIFTI_MODEL_TYPE_SURFACE"
  ..- attr(*, "SurfaceNumberOfVertices")= num 32492
 $ : num [1:135, 1:3] 49 50 48 49 50 48 49 50 48 49 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : NULL
  .. ..$ : chr [1:3] "i" "j" "k"
 $ : num [1:140, 1:3] 40 41 39 40 41 42 39 40 41 40 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : NULL
  .. ..$ : chr [1:3] "i" "j" "k"</code></pre>
</div>
</div>
<p>The first two areas are both left and right cortex and have an attribute saying their name, but the following subcortical areas are unnamed in this structure. This makes it impossible to tell explicitly which area each subcortical list belongs to just from this data structure.</p>
<p>To get around this, we can take advantage of the fact the cifti format is essentially a fancy XML file and just read the text information directly using <code>cifti_xml_txt</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb33"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>txt <span class="ot">&lt;-</span> <span class="fu">cifti_xml_txt</span>(<span class="st">'data/102109/Results/rfMRI_REST1_LR/rfMRI_REST1_LR_Atlas.dtseries.nii'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This gives us a single string with all of the text information from the cifti file in it. Looking at the cifti file in a text editor, we can see that each area name begins with the string “CIFTI_STRUCTURE_”. So to get all of the area names, we can extract strings that begin with “CIFTI_STRUCTURE_” using a regex.</p>
<div class="cell">
<div class="sourceCode" id="cb34"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>areas <span class="ot">&lt;-</span> <span class="fu">str_extract_all</span>(txt,<span class="st">'CIFTI_STRUCTURE_[A-Z_]+'</span>)[[<span class="dv">1</span>]]</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>areas</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code> [1] "CIFTI_STRUCTURE_CORTEX_LEFT"               
 [2] "CIFTI_STRUCTURE_CORTEX_RIGHT"              
 [3] "CIFTI_STRUCTURE_ACCUMBENS_LEFT"            
 [4] "CIFTI_STRUCTURE_ACCUMBENS_RIGHT"           
 [5] "CIFTI_STRUCTURE_AMYGDALA_LEFT"             
 [6] "CIFTI_STRUCTURE_AMYGDALA_RIGHT"            
 [7] "CIFTI_STRUCTURE_BRAIN_STEM"                
 [8] "CIFTI_STRUCTURE_CAUDATE_LEFT"              
 [9] "CIFTI_STRUCTURE_CAUDATE_RIGHT"             
[10] "CIFTI_STRUCTURE_CEREBELLUM_LEFT"           
[11] "CIFTI_STRUCTURE_CEREBELLUM_RIGHT"          
[12] "CIFTI_STRUCTURE_DIENCEPHALON_VENTRAL_LEFT" 
[13] "CIFTI_STRUCTURE_DIENCEPHALON_VENTRAL_RIGHT"
[14] "CIFTI_STRUCTURE_HIPPOCAMPUS_LEFT"          
[15] "CIFTI_STRUCTURE_HIPPOCAMPUS_RIGHT"         
[16] "CIFTI_STRUCTURE_PALLIDUM_LEFT"             
[17] "CIFTI_STRUCTURE_PALLIDUM_RIGHT"            
[18] "CIFTI_STRUCTURE_PUTAMEN_LEFT"              
[19] "CIFTI_STRUCTURE_PUTAMEN_RIGHT"             
[20] "CIFTI_STRUCTURE_THALAMUS_LEFT"             
[21] "CIFTI_STRUCTURE_THALAMUS_RIGHT"            </code></pre>
</div>
</div>
<p>The 21 area names matches the 21 list entries. If you are only looking for data from a subset of the areas listed here, you can grab those lists via indexing (i.e.&nbsp;data from the left and right hippocampus would be in <code>rest_cii$BrainModel[14]</code> and <code>rest_cii$BrainModel[15]</code>, respectively).</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>It’s important to note that the area names may not always begin with “CIFTI_STRUCTURE_” depending on who or what made them. You can easily open the cifti file in a text editor such as Notepad++ and search for the “BrainStructure” tags to see if there is a pattern to the area names.</p>
</div>
</div>
</section>
<section id="converting-to-data-frame" class="level3">
<h3 class="anchored" data-anchor-id="converting-to-data-frame">Converting to Data Frame</h3>
<p>If you are using other packages such as the <code>tidyverse</code> for analyzing cifti data, it would make sense to convert the cifti list structure to a data frame (or tibble) first for data wrangling. I recommend keeping cortical data separate from subcortical data because they do not share a common ID format. In other words, cortical cifti data are identified via single vertex numbers while subcortical cifti data are identified using 3 coordinate locations. Keeping cortical and subcortical data in the same data frame would have 4 ID columns that are not shared among all of the data. If you do not need any form of brainordinate identifier beyond the area name, then keeping cortical and subcortical data together is fine</p>
<p>Extracting cortical data from ciftis where the data is an array (such as thickness) is simple and straightforward.</p>
<div class="cell">
<div class="sourceCode" id="cb36"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>lhvert <span class="ot">&lt;-</span> <span class="fu">length</span>(thick_cii<span class="sc">$</span>BrainModel[[<span class="dv">1</span>]]) <span class="co"># number of left hemisphere vertices</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>rhvert <span class="ot">&lt;-</span> <span class="fu">length</span>(thick_cii<span class="sc">$</span>BrainModel[[<span class="dv">2</span>]]) <span class="co"># number of right hemisphere vertices</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>cortical_thick <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">hemi =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">'LH'</span>,<span class="st">'RH'</span>),<span class="at">times =</span> <span class="fu">c</span>(lhvert,rhvert)),</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">vertex =</span> <span class="fu">c</span>(thick_cii<span class="sc">$</span>BrainModel[[<span class="dv">1</span>]],</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>                                    thick_cii<span class="sc">$</span>BrainModel[[<span class="dv">2</span>]]), <span class="co"># concatenate the vertex numbers</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>                         <span class="at">thickness =</span> thick_cii<span class="sc">$</span>data[<span class="dv">1</span><span class="sc">:</span>(lhvert <span class="sc">+</span> rhvert)]) <span class="co"># get data for all vertices</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">glimpse</span>(cortical_thick))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code>Rows: 59,412
Columns: 3
$ hemi      &lt;chr&gt; "LH", "LH", "LH", "LH", "LH", "LH", "LH", "LH", "LH", "LH", …
$ vertex    &lt;dbl&gt; 0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 1…
$ thickness &lt;dbl&gt; 3.162518, 2.270701, 3.053933, 3.499338, 2.217890, 2.389992, …</code></pre>
</div>
<div class="cell-output-stdout">
<pre><code># A tibble: 6 × 3
  hemi  vertex thickness
  &lt;chr&gt;  &lt;dbl&gt;     &lt;dbl&gt;
1 LH         0      3.16
2 LH         1      2.27
3 LH         2      3.05
4 LH         3      3.50
5 LH         4      2.22
6 LH         5      2.39</code></pre>
</div>
</div>
<p>For this, we do need the hemisphere designation because vertex numbers are not unique across hemispheres. Because the array of thickness data can easily be converted to a column in a data frame, there’s very little other data wrangling to perform. This isn’t the case for 2D cifti data such as timeseries where there are a couple of extra steps needed to convert the timeseries matrix to a data frame itself.</p>
<div class="cell" data-hash="cifti-r_cache/html/cortical rest_3687ee8b6176a6489f0f172a8d4464b2">
<div class="sourceCode" id="cb39"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>lhvert <span class="ot">&lt;-</span> <span class="fu">length</span>(rest_cii<span class="sc">$</span>BrainModel[[<span class="dv">1</span>]]) <span class="co"># number of left hemisphere vertices</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>rhvert <span class="ot">&lt;-</span> <span class="fu">length</span>(rest_cii<span class="sc">$</span>BrainModel[[<span class="dv">2</span>]]) <span class="co"># number of right hemisphere vertices</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="co"># get the cortical data from the dataframe, name columns by their TR number, then convert to a tibble</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>cort_ts <span class="ot">&lt;-</span> rest_cii<span class="sc">$</span>data[<span class="dv">1</span><span class="sc">:</span>(lhvert<span class="sc">+</span>rhvert),] </span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(cort_ts) <span class="ot">&lt;-</span> <span class="fu">sprintf</span>(<span class="st">'TR_%s'</span>,<span class="fu">seq</span>(<span class="dv">1</span>,<span class="fu">ncol</span>(rest_cii<span class="sc">$</span>data)))</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>cort_ts <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(cort_ts)</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a><span class="co"># add vertex and hemisphere designation to time series</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>cortical_rest <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">hemi =</span> <span class="fu">rep</span>(areas[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>],<span class="at">times =</span> <span class="fu">c</span>(lhvert,rhvert)),</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>                        <span class="at">vertex =</span> <span class="fu">c</span>(rest_cii<span class="sc">$</span>BrainModel[[<span class="dv">1</span>]],</span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>                                   rest_cii<span class="sc">$</span>BrainModel[[<span class="dv">2</span>]]),</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>                        cort_ts)</span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>cortical_rest</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code># A tibble: 59,412 × 1,202
   hemi    vertex   TR_1   TR_2   TR_3   TR_4   TR_5   TR_6   TR_7   TR_8   TR_9
   &lt;chr&gt;    &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1 CIFTI_…      0 11080. 10631. 10815. 10822. 11066. 10718. 10729. 10740. 10828.
 2 CIFTI_…      1  9024.  8972.  8948.  9030.  9062.  9023.  8839.  8953.  8887.
 3 CIFTI_…      2  8399.  8398.  8435.  8393.  8499.  8435.  8403.  8445.  8406.
 4 CIFTI_…      3 13957. 13956. 14039. 14022. 13993. 13824. 13867. 14139. 13901.
 5 CIFTI_…      4  9830.  9831.  9716.  9945.  9747.  9920.  9875.  9820.  9757.
 6 CIFTI_…      5  8821.  8689.  8716.  8591.  8518.  8663.  8569.  8665.  8643.
 7 CIFTI_…      6 14528. 14574. 14175. 14593. 14271. 14448. 14380. 14337. 14237.
 8 CIFTI_…      8 12588. 12453. 12334. 12743. 11746. 12552. 12873. 12783. 12377.
 9 CIFTI_…      9  7188.  7202.  7196.  7201.  7205.  7216.  7188.  7180.  7125.
10 CIFTI_…     10 11486. 11930. 11223. 11407. 11931. 10985. 11667. 11963. 11468.
# … with 59,402 more rows, and 1,191 more variables: TR_10 &lt;dbl&gt;, TR_11 &lt;dbl&gt;,
#   TR_12 &lt;dbl&gt;, TR_13 &lt;dbl&gt;, TR_14 &lt;dbl&gt;, TR_15 &lt;dbl&gt;, TR_16 &lt;dbl&gt;,
#   TR_17 &lt;dbl&gt;, TR_18 &lt;dbl&gt;, TR_19 &lt;dbl&gt;, TR_20 &lt;dbl&gt;, TR_21 &lt;dbl&gt;,
#   TR_22 &lt;dbl&gt;, TR_23 &lt;dbl&gt;, TR_24 &lt;dbl&gt;, TR_25 &lt;dbl&gt;, TR_26 &lt;dbl&gt;,
#   TR_27 &lt;dbl&gt;, TR_28 &lt;dbl&gt;, TR_29 &lt;dbl&gt;, TR_30 &lt;dbl&gt;, TR_31 &lt;dbl&gt;,
#   TR_32 &lt;dbl&gt;, TR_33 &lt;dbl&gt;, TR_34 &lt;dbl&gt;, TR_35 &lt;dbl&gt;, TR_36 &lt;dbl&gt;,
#   TR_37 &lt;dbl&gt;, TR_38 &lt;dbl&gt;, TR_39 &lt;dbl&gt;, TR_40 &lt;dbl&gt;, TR_41 &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>For subcortical areas, there is a bit more wrangling to do since these brainordinates use i, j, and k positional values as opposed to single numbers, and there are 19 subcortical areas that will need to be replicated as opposed to just the two hemispheres.</p>
<div class="cell" data-hash="cifti-r_cache/html/subcortical rest_09f725317ab966417de94d735570ae59">
<div class="sourceCode" id="cb41"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate total number of cortical vertices to know how many rows to skip in the data field</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>cort_vert <span class="ot">&lt;-</span> <span class="fu">length</span>(rest_cii<span class="sc">$</span>BrainModel[[<span class="dv">1</span>]]) <span class="sc">+</span> <span class="fu">length</span>(rest_cii<span class="sc">$</span>BrainModel[[<span class="dv">2</span>]])</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="co"># get ordinate counts of all subcortical areas</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>subcortical_ordinate_count <span class="ot">&lt;-</span> <span class="fu">sapply</span>(rest_cii<span class="sc">$</span>BrainModel,nrow,<span class="at">simplify =</span> <span class="cn">TRUE</span>)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="co"># set up coordinates information with proper column names</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind,rest_cii<span class="sc">$</span>BrainModel[<span class="sc">-</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)])</span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(coords) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'i'</span>,<span class="st">'j'</span>,<span class="st">'k'</span>)</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(coords)</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a><span class="co"># get the subcortical data from the dataframe, name columns by their TR number, then convert to a tibble</span></span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>subcort_ts <span class="ot">&lt;-</span> rest_cii<span class="sc">$</span>data[<span class="sc">-</span>(<span class="dv">1</span><span class="sc">:</span>cort_vert),] <span class="co"># -(1:(lhvert+rhvert)) removes rows from index 1 to cort_vert</span></span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(subcort_ts) <span class="ot">&lt;-</span> <span class="fu">sprintf</span>(<span class="st">'TR_%s'</span>,<span class="fu">seq</span>(<span class="dv">1</span>,<span class="fu">ncol</span>(rest_cii<span class="sc">$</span>data)))</span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>subcort_ts <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(subcort_ts)</span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>subcortical_rest <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">area =</span> <span class="fu">rep</span>(areas[<span class="sc">-</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)], <span class="at">times =</span> subcortical_ordinate_count[<span class="sc">-</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>)]),</span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a>                           coords,</span>
<span id="cb41-19"><a href="#cb41-19" aria-hidden="true" tabindex="-1"></a>                           subcort_ts)</span>
<span id="cb41-20"><a href="#cb41-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-21"><a href="#cb41-21" aria-hidden="true" tabindex="-1"></a>subcortical_rest</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-stdout">
<pre><code># A tibble: 31,870 × 1,204
   area           i     j     k   TR_1   TR_2   TR_3   TR_4   TR_5   TR_6   TR_7
   &lt;chr&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1 CIFTI_STR…    49    66    28 15240. 14360. 15391. 15032. 12862. 14726. 15090.
 2 CIFTI_STR…    50    66    28 15638. 15564. 16683. 14691. 14413. 14595. 14603.
 3 CIFTI_STR…    48    67    28 14189. 13153. 12935. 13628. 13604. 13070. 13693.
 4 CIFTI_STR…    49    67    28 14181. 13154. 12941. 13613. 13599. 13065. 13688.
 5 CIFTI_STR…    50    67    28 13525. 13277. 13470. 12208. 13158. 12644. 13300.
 6 CIFTI_STR…    48    65    29 14615. 14598. 15121. 14311. 16033. 14690. 15387.
 7 CIFTI_STR…    49    65    29 14624. 13710. 15236. 14888. 14645. 14879. 13985.
 8 CIFTI_STR…    50    65    29 15113. 14616. 15959. 14786. 14585. 14742. 14252.
 9 CIFTI_STR…    48    66    29 15866. 15666. 16395. 15861. 14309. 15825. 15285.
10 CIFTI_STR…    49    66    29 15238. 14371. 15306. 14986. 12904. 14845. 15046.
# … with 31,860 more rows, and 1,193 more variables: TR_8 &lt;dbl&gt;, TR_9 &lt;dbl&gt;,
#   TR_10 &lt;dbl&gt;, TR_11 &lt;dbl&gt;, TR_12 &lt;dbl&gt;, TR_13 &lt;dbl&gt;, TR_14 &lt;dbl&gt;,
#   TR_15 &lt;dbl&gt;, TR_16 &lt;dbl&gt;, TR_17 &lt;dbl&gt;, TR_18 &lt;dbl&gt;, TR_19 &lt;dbl&gt;,
#   TR_20 &lt;dbl&gt;, TR_21 &lt;dbl&gt;, TR_22 &lt;dbl&gt;, TR_23 &lt;dbl&gt;, TR_24 &lt;dbl&gt;,
#   TR_25 &lt;dbl&gt;, TR_26 &lt;dbl&gt;, TR_27 &lt;dbl&gt;, TR_28 &lt;dbl&gt;, TR_29 &lt;dbl&gt;,
#   TR_30 &lt;dbl&gt;, TR_31 &lt;dbl&gt;, TR_32 &lt;dbl&gt;, TR_33 &lt;dbl&gt;, TR_34 &lt;dbl&gt;,
#   TR_35 &lt;dbl&gt;, TR_36 &lt;dbl&gt;, TR_37 &lt;dbl&gt;, TR_38 &lt;dbl&gt;, TR_39 &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>We pretty much set up each individual component of the subcortical data frame outside of the <code>tibble</code> command because of the wrangling, so if you need to conserve memory be sure to delete the intermediate variables with <code>rm</code>.</p>
<p>Remember, these steps are only creating a dataframe for a single person, but the size of the cortical and subcortical resting state data frames are 1.097847^{8} and this is not including other demographic variables such as participant ID and group. As opposed to creating full data frames for all your participants and then filtering afterwards, it will be useful to filter and curate data for each participant as they are being imported using a function.</p>

</section>
</section>
</main>
<!-- /main column -->
<script type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
    } else {
      disableStylesheet(alternateStylesheets);
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } 
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    setTimeout(function() {
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->


</body></html>